name = "beacon-cm"
main = "_worker.js"
compatibility_date = "2024-11-04"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[[routes]]
pattern = "beacon.jingzhevpn.de5.net/*"
zone_name = "jingzhevpn.de5.net"

[vars]
ADMIN = "jingzhenb666"

[[kv_namespaces]]
binding = "KV"
id = "19cdddfd5dd4465993cd6e8bbef1713f"

[[d1_databases]]
binding = "DB"
database_name = "jingzhe"
database_id = "f1b1fba9-1b02-42c5-96a2-004a89e1eaee"

[[triggers]]
crons = ["0 */6 * * *"]
